name: Destroy Infraestrutura Didático

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Selecione a branch para executar"
        required: true
        default: "main"

env:
  TERRAFORM_VERSION: 1.7.5
  WORKING_DIR: infra
  BUCKET_NAME: bucket-html-tonho

jobs:
  checkout:
    name: 🔄 Checkout do Código
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

  auth:
    name: 🔐 Autenticação com GCP
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Autenticar com GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Instalar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

  terraform_destroy:
    name: 💣 Terraform Destroy
    runs-on: ubuntu-latest
    needs: auth
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Validar Terraform
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

      - name: Destruir infraestrutura
        run: terraform destroy -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
        working-directory: ${{ env.WORKING_DIR }}

  finalizar:
    name: ✅ Finalizar e exibir mensagem
    runs-on: ubuntu-latest
    needs: terraform_destroy
    steps:
      - name: Confirmação de destruição
        run: |
          echo "🧹 Infraestrutura destruída com sucesso!"
          echo "🧾 Bucket destruído: ${{ env.BUCKET_NAME }}"
