name: Deploy HTML Bucket

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Selecione a branch para executar"
        required: true
        default: "main"

jobs:
  deploy-html:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Criar arquivo de credenciais da GCP
        run: echo "${{ secrets.GCP_SA_KEY }}" > /tmp/key.json

      - name: Autenticar no GCP via ADC
        run: |
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Inicializar Terraform
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json

      - name: Validar Terraform
        run: terraform validate
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json

      - name: Aplicar Terraform (criação do bucket)
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json

      - name: Copiar index.html para o bucket
        run: |
          BUCKET_NAME=$(terraform output -raw html_bucket_name)
          gsutil cp ../calculadora/index.html gs://$BUCKET_NAME/index.html
          gsutil acl ch -u AllUsers:R gs://$BUCKET_NAME/index.html
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json

      - name: Notificar sucesso no Discord
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "✅ Deploy do bucket HTML realizado com sucesso!"}' \
          https://discord.com/api/webhooks/1414793316083433663/DqRtpwytv1u3ROdhKxhwGUMZYA0leFFCKcZd7PcNc4J45HtqkmpqESBCGVcDl08C0nFu

      - name: Notificar falha no Discord
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "❌ Falha no deploy do bucket HTML. Verifique a pipeline no GitHub Actions."}' \
          https://discord.com/api/webhooks/1414793316083433663/DqRtpwytv1u3ROdhKxhwGUMZYA0leFFCKcZd7PcNc4J45HtqkmpqESBCGVcDl08C0nFu
